export const getCountries = () => ({
    alaska: {
        neighbours: ["northwest_territory", "alberta", "kamchatka"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    northwest_territory: {
        neighbours: ["alaska", "alberta", "ontario", "greenland"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    greenland: {
        neighbours: ["quebec", "ontario", "northwest_territory", "iceland"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    quebec: {
        neighbours: ["greenland", "ontario", "eastern_united_states"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    ontario: {
        neighbours: [
            "quebec",
            "greenland",
            "northwest_territory",
            "alberta",
            "western_united_states",
            "eastern_united_states",
        ],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    alberta: {
        neighbours: [
            "alaska",
            "northwest_territory",
            "ontario",
            "western_united_states",
        ],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    western_united_states: {
        neighbours: [
            "alberta",
            "ontario",
            "eastern_united_states",
            "central_america",
        ],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    eastern_united_states: {
        neighbours: [
            "quebec",
            "ontario",
            "western_united_states",
            "central_america",
        ],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    central_america: {
        neighbours: [
            "western_united_states",
            "eastern_united_states",
            "venezuela",
        ],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    venezuela: {
        neighbours: ["central_america", "brazil", "peru"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    brazil: {
        neighbours: ["venezuela", "peru", "argentina", "north_africa"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    peru: {
        neighbours: ["brazil", "venezuela", "argentina"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    argentina: {
        neighbours: ["peru", "brazil"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    north_africa: {
        neighbours: [
            "brazil",
            "western_europe",
            "southern_europe",
            "egypt",
            "east_africa",
            "congo",
        ],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    egypt: {
        neighbours: [
            "middle_east",
            "southern_europe",
            "western_europe",
            "north_africa",
            "east_africa",
        ],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    east_africa: {
        neighbours: [
            "egypt",
            "north_africa",
            "congo",
            "south_africa",
            "madagascar",
        ],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    congo: {
        neighbours: ["south_africa", "east_africa", "north_africa"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    south_africa: {
        neighbours: ["madagascar", "east_africa", "congo"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    madagascar: {
        neighbours: ["south_africa", "east_africa"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    western_europe: {
        neighbours: [
            "north_africa",
            "southern_europe",
            "northern_europe",
            "great_britain",
        ],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    southern_europe: {
        neighbours: [
            "western_europe",
            "north_africa",
            "egypt",
            "middle_east",
            "ukraine",
            "northern_europe",
        ],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    northern_europe: {
        neighbours: [
            "great_britain",
            "western_europe",
            "southern_europe",
            "ukraine",
            "scandinavia",
        ],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    great_britain: {
        neighbours: [
            "western_europe",
            "northern_europe",
            "scandinavia",
            "iceland",
        ],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    iceland: {
        neighbours: ["greenland", "scandinavia", "great_britain"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    ukraine: {
        neighbours: [
            "scandinavia",
            "northern_europe",
            "southern_europe",
            "middle_east",
            "afghanistan",
            "ural",
        ],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    middle_east: {
        neighbours: [
            "egypt",
            "southern_europe",
            "ukraine",
            "afghanistan",
            "india",
        ],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    afghanistan: {
        neighbours: ["middle_east", "ukraine", "ural", "china", "india"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    ural: {
        neighbours: ["ukraine", "afghanistan", "china", "siberia"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    india: {
        neighbours: ["middle_east", "afghanistan", "china", "siam"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    china: {
        neighbours: [
            "india",
            "afghanistan",
            "ural",
            "siberia",
            "mongolia",
            "siam",
        ],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    siberia: {
        neighbours: ["yakursk", "irkutsk", "mongolia", "china", "ural"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    yakursk: {
        neighbours: ["siberia", "irkutsk", "kamchatka"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    irkutsk: {
        neighbours: ["siberia", "yakursk", "kamchatka", "mongolia"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    mongolia: {
        neighbours: ["kamchatka", "irkutsk", "siberia", "china", "japan"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    japan: {
        neighbours: ["mongolia", "kamchatka"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    kamchatka: {
        neighbours: ["japan", "alaska", "yakursk", "irkutsk", "mongolia"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    siam: {
        neighbours: ["india", "china", "indonesia"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    indonesia: {
        neighbours: ["siam", "new_guinea", "western_australia"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    new_guinea: {
        neighbours: ["indonesia", "western_australia", "eastern_australia"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    western_australia: {
        neighbours: ["indonesia", "new_guinea", "eastern_australia"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    eastern_australia: {
        neighbours: ["new_guinea", "western_australia"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
    scandinavia: {
        neighbours: ["ukraine", "northern_europe", "iceland", "great_britain"],
        owner: null,
        tanks: 0,
        color: "grey",
    },
})

export const countries = [
    "alaska",
    "northwest_territory",
    "greenland",
    "quebec",
    "ontario",
    "alberta",
    "western_united_states",
    "eastern_united_states",
    "central_america",
    "venezuela",
    "brazil",
    "peru",
    "argentina",
    "north_africa",
    "egypt",
    "east_africa",
    "congo",
    "south_africa",
    "madagascar",
    "western_europe",
    "southern_europe",
    "northern_europe",
    "great_britain",
    "iceland",
    "ukraine",
    "middle_east",
    "afghanistan",
    "ural",
    "india",
    "china",
    "siberia",
    "yakursk",
    "irkutsk",
    "mongolia",
    "japan",
    "kamchatka",
    "siam",
    "indonesia",
    "new_guinea",
    "western_australia",
    "eastern_australia",
    "scandinavia",
]

export const continents = {
    north_america: {
        countries: [
            "alaska",
            "northwest_territory",
            "greenland",
            "quebec",
            "ontario",
            "alberta",
            "western_united_states",
            "eastern_united_states",
            "central_america",
        ],
        tanks: 5,
    },
    south_america: {
        countries: ["venezuela", "brazil", "peru", "argentina"],
        tanks: 2,
    },
    europe: {
        countries: [
            "western_europe",
            "southern_europe",
            "northern_europe",
            "great_britain",
            "iceland",
            "ukraine",
            "scandinavia",
        ],
        tanks: 5,
    },
    asia: {
        countries: [
            "middle_east",
            "afghanistan",
            "ural",
            "india",
            "china",
            "siberia",
            "yakursk",
            "irkutsk",
            "mongolia",
            "japan",
            "kamchatka",
            "siam",
        ],
        tanks: 7,
    },
    africa: {
        countries: [
            "north_africa",
            "egypt",
            "east_africa",
            "congo",
            "south_africa",
            "madagascar",
        ],
        tanks: 3,
    },
    oceania: {
        countries: [
            "indonesia",
            "new_guinea",
            "western_australia",
            "eastern_australia",
        ],
        tanks: 2,
    },
}

export const cards = [
    { country: "alaska", type: "cannone" },
    { country: "northwest_territory", type: "fante" },
    { country: "greenland", type: "fante" },
    { country: "quebec", type: "fante" },
    { country: "ontario", type: "cannone" },
    { country: "alberta", type: "cannone" },
    { country: "western_united_states", type: "fante" },
    { country: "eastern_united_states", type: "cannone" },
    { country: "central_america", type: "fante" },
    { country: "venezuela", type: "cannone" },
    { country: "brazil", type: "fante" },
    { country: "peru", type: "fante" },
    { country: "argentina", type: "cannone" },
    { country: "north_africa", type: "cannone" },
    { country: "egypt", type: "fante" },
    { country: "east_africa", type: "cannone" },
    { country: "congo", type: "cavaliere" },
    { country: "south_africa", type: "fante" },
    { country: "madagascar", type: "cavaliere" },
    { country: "western_europe", type: "fante" },
    { country: "southern_europe", type: "cavaliere" },
    { country: "northern_europe", type: "cannone" },
    { country: "great_britain", type: "cavaliere" },
    { country: "iceland", type: "cavaliere" },
    { country: "ukraine", type: "cavaliere" },
    { country: "middle_east", type: "cavaliere" },
    { country: "afghanistan", type: "cannone" },
    { country: "ural", type: "cannone" },
    { country: "india", type: "fante" },
    { country: "china", type: "cavaliere" },
    { country: "siberia", type: "cavaliere" },
    { country: "yakursk", type: "cavaliere" },
    { country: "irkutsk", type: "cannone" },
    { country: "mongolia", type: "cannone" },
    { country: "japan", type: "fante" },
    { country: "kamchatka", type: "cavaliere" },
    { country: "siam", type: "cannone" },
    { country: "indonesia", type: "fante" },
    { country: "new_guinea", type: "cavaliere" },
    { country: "western_australia", type: "cavaliere" },
    { country: "eastern_australia", type: "cavaliere" },
    { country: "scandinavia", type: "fante" },
    { type: "jolly" },
    { type: "jolly" },
]

export const countryDots = {
    afghanistan: "g1651",
    alaska: "g1779-1",
    alberta: "g1779-6",
    argentina: "g1779-62",
    brazil: "g1779-98",
    central_america: "g1779-65",
    china: "g1707",
    congo: "g1779-0",
    east_africa: "g1779-4",
    eastern_australia: "g1763",
    eastern_united_states: "g1779-11",
    egypt: "g1779-93",
    great_britain: "g1595",
    greenland: "g1779-8",
    iceland: "g1643",
    india: "g1715",
    indonesia: "g1739",
    irkutsk: "g1683",
    japan: "g1699",
    kamchatka: "g1779-45",
    madagascar: "g1771",
    middle_east: "g1731",
    mongolia: "g1691",
    new_guinea: "g1747",
    north_africa: "g1779-9",
    northern_europe: "g1619",
    northwest_territory: "g1779-42",
    ontario: "g1779-7",
    peru: "g1779-2",
    quebec: "g1779-70",
    scandinavia: "g1635",
    siam: "g1723",
    siberia: "g1667",
    south_africa: "g1779",
    southern_europe: "g1611",
    ukraine: "g1627",
    ural: "g1659",
    venezuela: "g1779-04",
    western_australia: "g1755",
    western_europe: "g1603",
    western_united_states: "g1779-60",
    yakursk: "g1675",
}

export const countryCenters = {
    afghanistan: [504.02200000000005, 194.987],
    alaska: [59.13200000000003, 83.261],
    alberta: [120.20800000000003, 126.395],
    argentina: [194.985, 408.177],
    brazil: [237.75, 333.875],
    central_america: [131.37500000000003, 243.75],
    china: [588.415, 223.98899999999998],
    congo: [405.625, 374.375],
    east_africa: [445.61, 349.62199999999996],
    eastern_australia: [680.461, 408.318],
    eastern_united_states: [176.37500000000003, 197.125],
    egypt: [403.875, 292.5],
    great_britain: [305.915, 160.427],
    greenland: [261.45300000000003, 59.92699999999999],
    iceland: [319.60900000000004, 104.779],
    india: [546.287, 266.86199999999997],
    indonesia: [630.433, 366.74],
    irkutsk: [596.547, 135.24699999999999],
    japan: [684.935, 176.613],
    kamchatka: [663.375, 85.49999999999999],
    madagascar: [476.58000000000004, 436.26699999999994],
    middle_east: [462.36, 274.21799999999996],
    mongolia: [609.098, 179.26399999999998],
    new_guinea: [679.223, 347.825],
    north_africa: [348.625, 309.25],
    northern_europe: [376.27200000000005, 176.237],
    northwest_territory: [109.37500000000003, 81.37499999999999],
    ontario: [165.532, 134.809],
    peru: [194.63100000000003, 352.846],
    quebec: [219, 132.625],
    scandinavia: [375.824, 103.011],
    siam: [605.154, 286.307],
    siberia: [554.938, 98.582],
    south_africa: [410.08000000000004, 441.01699999999994],
    southern_europe: [394.02200000000005, 221.737],
    ukraine: [447.77200000000005, 140.487],
    ural: [518.522, 128.987],
    venezuela: [179.51700000000002, 285.406],
    western_australia: [647.58, 424.01699999999994],
    western_europe: [334.37600000000003, 207.803],
    western_united_states: [121.87500000000003, 180.125],
    yakursk: [605.5630000000001, 74.082],
}
